<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-APP06KDG" failures="1" tests="5" name="com.naveenautomationlabs.AutomationFramework.YourStoreTest" time="7.244" errors="0" timestamp="2023-06-25T22:29:44 EDT" skipped="4">
  <testcase classname="com.naveenautomationlabs.AutomationFramework.YourStoreTest" name="testMovingDots" time="7.244">
    <failure message="DOts did not move did not expect [11] but found [11]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: DOts did not move did not expect [11] but found [11]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at com.naveenautomationlabs.AutomationFramework.YourStoreTest.testMovingDots(YourStoreTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMovingDots -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.YourStoreTest" name="testFailure">
    <skipped/>
  </testcase> <!-- testFailure -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.YourStoreTest" name="validateSearchProduct">
    <skipped/>
  </testcase> <!-- validateSearchProduct -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.YourStoreTest" name="validateLoginUsingValidCredentials">
    <skipped/>
  </testcase> <!-- validateLoginUsingValidCredentials -->
  <system-out/>
  <testcase classname="com.naveenautomationlabs.AutomationFramework.YourStoreTest" name="vaidateMovingElement">
    <skipped/>
  </testcase> <!-- vaidateMovingElement -->
  <system-out/>
</testsuite> <!-- com.naveenautomationlabs.AutomationFramework.YourStoreTest -->
